### ISSUE TITLE
Current release (1.1.1) fails when installing in WeeWX 5.0.0b17

### ISSUE THREAD

**Issue by G400** [michael-slx/weewx-weatherlink-live#31]
Current release (1.1.1) fails when installing in WeeWX 5.0.0b17

sudo weectl extension install weewx-weatherlink-live-v1.1.1.tar.xz
Request to install 'weewx-weatherlink-live-v1.1.1.tar.xz'.
Extracting from tar archive weewx-weatherlink-live-v1.1.1.tar.xz
Traceback (most recent call last):
File "/usr/share/weewx/weectl.py", line 74, in
main()
File "/usr/share/weewx/weectl.py", line 66, in main
namespace.func(namespace)
File "/usr/share/weewx/weectllib/extension_cmd.py", line 112, in install_extension
ext.install_extension(namespace.source)
File "/usr/share/weewx/weecfg/extension.py", line 122, in install_extension
extension_name = self._install_from_file(extension_path, filetype)
File "/usr/share/weewx/weecfg/extension.py", line 154, in _install_from_file
extension_name = self.install_from_dir(extension_dir)
File "/usr/share/weewx/weecfg/extension.py", line 201, in install_from_dir
save_config |= self._inject_config(installer['config'], extension_name)
KeyError: 'config'

**Comment by michael-slx** [comment]
Fixed in [`v1.1.2`](https://github.com/michael-slx/weewx-weatherlink-live/releases/tag/v1.1.2).
